CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    descripcion VARCHAR(200) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    startline TIMESTAMPTZ,
    deadline TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    auth_provider VARCHAR(40) NOT NULL DEFAULT 'local',
    google_sub VARCHAR(255),
    avatar_url TEXT,
    given_name VARCHAR(255),
    family_name VARCHAR(255),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ
);

-- Cuenta inicial para el acceso local. La contraseña se almacena con PBKDF2.
INSERT INTO public.users (
    nombre,
    apellido,
    email,
    descripcion,
    password,
    status,
    auth_provider,
    email_verified
)
VALUES (
    'Administrador',
    'Local',
    'admin@stockassistant.app',
    'Cuenta local de administracion de Proyecto Jupiter',
    'pbkdf2_sha256$150000$W-hlMXWZEWti4S9MffIs2Q$ZtbTCJr0CBw4jnULU1E81snKcz25w3HjzMw44pujhkM',
    1,
    'local',
    TRUE
)
ON CONFLICT (email) DO NOTHING;
