version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: supply_chain_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/01_create_db.sql:/docker-entrypoint-initdb.d/01_create_db.sql
      - ./postgres/02_create_tables.sql:/docker-entrypoint-initdb.d/02_create_tables.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres/logs:/var/log/postgresql  # Monta un volumen local para logs
      - ./init-scripts:/docker-entrypoint-initdb.d  # Scripts de inicialización
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - supply_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d supply_chain"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: supply_chain_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@supplychain.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - supply_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  supply_network:
    driver: bridge