import { FormEvent, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { addClientAddress, createMasterRecord, deleteClientAddress, fetchClientAddresses, fetchMasterRecords, updateClientAddress, updateMasterRecord } from "../api";
import type { ClientAddress, MasterRecord } from "../types";
import MasterDataEditorModal from "./components/MasterDataEditorModal";

const addressFields = [{ key: "address_line_1", label: "Dirección", required: true }, { key: "address_line_2", label: "Complemento" }, { key: "city", label: "Ciudad", required: true }, { key: "state_province", label: "Provincia / estado" }, { key: "postal_code", label: "Código postal" }, { key: "country_code", label: "Código país", required: true, placeholder: "ES" }, { key: "country_name", label: "País" }, { key: "contact_name", label: "Contacto" }, { key: "contact_phone", label: "Teléfono" }, { key: "contact_email", label: "Email" }, { key: "notes", label: "Notas", type: "textarea" as const }];
const addressTypes = ["Dirección principal", "Dirección por defecto", "Dirección de entrega", "Dirección de Recogida"];

export default function ClientDetailPage() {
  const clientId = Number(useParams().clientId);
  const [client, setClient] = useState<MasterRecord | null>(null); const [types, setTypes] = useState<MasterRecord[]>([]); const [addresses, setAddresses] = useState<ClientAddress[]>([]); const [values, setValues] = useState<Record<string, unknown>>({}); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { try { const [clients, clientTypes, clientAddresses] = await Promise.all([fetchMasterRecords("clients"), fetchMasterRecords("client-types"), fetchClientAddresses(clientId)]); setClient(clients.find((item) => item.id === clientId) ?? null); setTypes(clientTypes); setAddresses(clientAddresses); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo cargar el cliente."); } };
  useEffect(() => { if (Number.isInteger(clientId) && clientId > 0) void load(); }, [clientId]);
  const updateType = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!client) return; setSaving(true); try { await updateMasterRecord("clients", client.id, { fk_type_client: Number(client.fk_type_client) }); await load(); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo actualizar el tipo."); } finally { setSaving(false); } };
  const saveAddress = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const { address_type, ...addressValues } = values; const address = await createMasterRecord("global-addresses", addressValues); await addClientAddress(clientId, address.id, String(address_type)); setValues({}); await load(); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo guardar la dirección."); } finally { setSaving(false); } };
  return <div className="grid client-detail"><section className="card"><p className="section-label">Configuración · Clientes</p><h3>{client?.name ? String(client.name) : "Detalle de cliente"}</h3>{client && <p className="muted">Código de cliente: {String(client.client_code ?? "Sin asignar")}</p>}<Link className="chip-btn" to="/maestros/clientes">Volver a clientes</Link>{error && <p className="error-line">{error}</p>} {client && <form className="quick-row" onSubmit={updateType}><label className="field-label">Tipo de cliente<select value={String(client.fk_type_client)} onChange={(event) => setClient({ ...client, fk_type_client: Number(event.target.value) })}>{types.map((type) => <option key={type.id} value={type.id}>{String(type.name)}</option>)}</select></label><button className="primary-btn" disabled={saving} type="submit">Guardar tipo</button></form>}</section><section className="card"><div className="actions-row"><div><p className="section-label">Direcciones</p><h3>Direcciones del cliente</h3></div><button className="primary-btn" onClick={() => setValues({ address_type: "Dirección principal" })} type="button">Nueva dirección</button></div>{addresses.length ? <div className="master-table">{addresses.map((address) => <div className="master-row" key={address.id}><p><strong>{address.address_type}</strong><span>{address.address_line_1}{address.address_line_2 ? `, ${address.address_line_2}` : ""}</span><small>{address.city}, {address.country_code} · Global #{address.global_address_id}</small></p><div className="actions-row"><select aria-label="Tipo de dirección" defaultValue={address.address_type} onChange={(event) => void updateClientAddress(clientId, address.id, event.target.value).then(load).catch((err) => setError(err.message))}>{addressTypes.map((type) => <option key={type}>{type}</option>)}</select><button className="danger-btn" onClick={() => void deleteClientAddress(clientId, address.id).then(load).catch((err) => setError(err.message))} type="button">Quitar</button></div></div>)}</div> : <p className="muted">Este cliente aún no tiene direcciones asociadas.</p>}</section>{Object.keys(values).length > 0 && <MasterDataEditorModal title="dirección global" fields={[...addressFields, { key: "address_type", label: "Tipo de dirección", type: "select", required: true, options: addressTypes.map((type) => ({ value: type, label: type })) }]} record={null} values={values} saving={saving} error={error} onChange={(key, value) => setValues((current) => ({ ...current, [key]: value }))} onSubmit={(event) => void saveAddress(event)} onClose={() => setValues({})} />}</div>;
}
