import { FormEvent, useEffect, useState } from "react";
import BootstrapTable from "react-bootstrap-table-next";
import { addClientAddress, createMasterRecord, deleteClientAddress, deleteMasterRecord, fetchClientAddresses, fetchMasterRecords, updateClientAddress, updateMasterRecord } from "../api";
import type { ClientAddress, MasterRecord } from "../types";
import ClientAddressEditorModal from "./components/ClientAddressEditorModal";
import ClientEditorModal from "./components/ClientEditorModal";

export default function ClientsPage() {
  const [clients, setClients] = useState<MasterRecord[]>([]); const [types, setTypes] = useState<MasterRecord[]>([]); const [selected, setSelected] = useState<MasterRecord | null>(null); const [addresses, setAddresses] = useState<ClientAddress[]>([]); const [clientValues, setClientValues] = useState<Record<string, unknown>>({}); const [addressValues, setAddressValues] = useState<Record<string, unknown>>({}); const [editingAddress, setEditingAddress] = useState<ClientAddress | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { try { const [nextClients, nextTypes] = await Promise.all([fetchMasterRecords("clients"), fetchMasterRecords("client-types")]); setClients(nextClients); setTypes(nextTypes); setSelected((current) => nextClients.find((item) => item.id === current?.id) ?? null); } catch (err) { setError(err instanceof Error ? err.message : "No se pudieron cargar los clientes."); } };
  const loadAddresses = async (client: MasterRecord | null) => { if (!client) return setAddresses([]); try { setAddresses(await fetchClientAddresses(client.id)); } catch (err) { setError(err instanceof Error ? err.message : "No se pudieron cargar las direcciones."); } };
  useEffect(() => { void load(); }, []); useEffect(() => { void loadAddresses(selected); }, [selected?.id]);
  const saveClient = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { if (clientValues.id) await updateMasterRecord("clients", Number(clientValues.id), { client_code: clientValues.client_code, name: clientValues.name, description: clientValues.description, fk_type_client: Number(clientValues.fk_type_client) }); else await createMasterRecord("clients", { client_code: clientValues.client_code, name: clientValues.name, description: clientValues.description, fk_type_client: Number(clientValues.fk_type_client) }); setClientValues({}); await load(); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo guardar el cliente."); } finally { setSaving(false); } };
  const saveAddress = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; setSaving(true); try { const { address_type, id: _associationId, global_address_id: _globalAddressId, ...globalValues } = addressValues; if (editingAddress) { await updateMasterRecord("global-addresses", editingAddress.global_address_id, globalValues); await updateClientAddress(selected.id, editingAddress.id, String(address_type)); } else { const global = await createMasterRecord("global-addresses", globalValues); await addClientAddress(selected.id, global.id, String(address_type)); } setAddressValues({}); setEditingAddress(null); await loadAddresses(selected); await load(); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo guardar la dirección."); } finally { setSaving(false); } };
  const columns = [{ dataField: "id", text: "ID", sort: true }, { dataField: "client_code", text: "Código de cliente", sort: true }, { dataField: "name", text: "Cliente", sort: true }, { dataField: "fk_type_client", text: "Tipo", formatter: (value: number) => types.find((type) => type.id === value)?.name ?? value }, { dataField: "actions", text: "Acciones", isDummyField: true, formatter: (_: unknown, row: MasterRecord) => <div className="actions-row"><button className="chip-btn" onClick={() => setClientValues({ id: row.id, client_code: row.client_code ?? "", name: row.name, description: row.description ?? "", fk_type_client: row.fk_type_client })} type="button">Editar</button><button className="danger-btn" disabled={Boolean(row.is_in_use)} onClick={() => void deleteMasterRecord("clients", row.id).then(load).catch((err) => setError(err.message))} type="button">Borrar</button></div> }];
  return <div className="grid clients-master-detail"><section className="card"><div className="actions-row"><div><p className="section-label">Configuración · Clientes</p><h3>Clientes</h3></div><button className="primary-btn" onClick={() => setClientValues({ client_code: "", name: "", description: "", fk_type_client: types.find((type) => type.id === 1)?.id ?? types[0]?.id ?? "" })} type="button">Agregar cliente</button></div>{error && <p className="error-line">{error}</p>}<div className="master-table-wrapper"><BootstrapTable keyField="id" data={clients} columns={columns} rowEvents={{ onClick: (_event: unknown, row: MasterRecord) => setSelected(row) }} classes="users-table master-data-table" bordered={false} noDataIndication="No hay clientes." /></div></section><section className="card"><div className="client-address-tab">Direcciones{selected ? ` · ${String(selected.name)}` : ""}</div>{selected ? <><div className="actions-row"><p className="muted">Direcciones asociadas al cliente seleccionado.</p><button className="primary-btn" onClick={() => { setEditingAddress(null); setAddressValues({ address_type: "Dirección principal", country_code: "ES" }); }} type="button">Agregar dirección</button></div><div className="master-table-wrapper"><BootstrapTable keyField="id" data={addresses} columns={[{ dataField: "address_type", text: "Tipo" }, { dataField: "address_line_1", text: "Dirección" }, { dataField: "city", text: "Ciudad" }, { dataField: "country_code", text: "País" }, { dataField: "actions", text: "Acciones", isDummyField: true, formatter: (_: unknown, row: ClientAddress) => <div className="actions-row"><button className="chip-btn" onClick={() => { setEditingAddress(row); setAddressValues({ ...row }); }} type="button">Editar</button><button className="danger-btn" onClick={() => void deleteClientAddress(selected.id, row.id).then(async () => { await loadAddresses(selected); await load(); }).catch((err) => setError(err.message))} type="button">Quitar</button></div> }]} classes="users-table master-data-table" bordered={false} noDataIndication="No hay direcciones asociadas." /></div></> : <p className="muted">Selecciona un cliente en la tabla superior para ver sus direcciones.</p>}</section>{Object.keys(clientValues).length > 0 && <ClientEditorModal record={clientValues.id ? { id: Number(clientValues.id) } : null} types={types} values={clientValues} saving={saving} error={error} onChange={(key, value) => setClientValues((current) => ({ ...current, [key]: value }))} onSubmit={(event) => void saveClient(event)} onClose={() => setClientValues({})} />}{Object.keys(addressValues).length > 0 && <ClientAddressEditorModal record={editingAddress ? { id: editingAddress.id } : null} values={addressValues} saving={saving} error={error} onChange={(key, value) => setAddressValues((current) => ({ ...current, [key]: value }))} onSubmit={(event) => void saveAddress(event)} onClose={() => { setAddressValues({}); setEditingAddress(null); }} />}</div>;
}
