from __future__ import annotations

import logging
import os
import time
from contextlib import contextmanager
from typing import Any, Generator

import psycopg2

logger = logging.getLogger("api.db")


def _get_env(*keys: str, default: str) -> str:
    for key in keys:
        value = os.getenv(key)
        if value:
            return value
    return default


def _connect_with_retries(host: str, port: int, db_name: str, user: str, password: str):
    max_retries = int(_get_env("POSTGRES_CONNECT_RETRIES", default="10"))
    retry_delay_seconds = float(_get_env("POSTGRES_RETRY_DELAY_SECONDS", default="1"))

    for attempt in range(1, max_retries + 1):
        try:
            logger.info(
                "event=db_connect host=%s port=%s db=%s user=%s attempt=%s/%s",
                host,
                port,
                db_name,
                user,
                attempt,
                max_retries,
            )
            return psycopg2.connect(
                host=host,
                port=port,
                dbname=db_name,
                user=user,
                password=password,
            )
        except psycopg2.OperationalError:
            if attempt == max_retries:
                raise
            sleep_seconds = retry_delay_seconds * attempt
            logger.warning(
                "event=db_connect_retry host=%s db=%s attempt=%s/%s wait_seconds=%.2f",
                host,
                db_name,
                attempt,
                max_retries,
                sleep_seconds,
            )
            time.sleep(sleep_seconds)


def _database_name(default: str = "supply_chain") -> str:
    return _get_env("POSTGRES_DB_NAME", "DB_NAME", "POSTGRES_DB", default=default)


def _get_postgres_connection_server(host: str = "postgres", db_name: str | None = None):
    resolved_host = _get_env("POSTGRES_HOST", "DB_HOST", default=host)
    resolved_port = int(_get_env("POSTGRES_PORT", "DB_PORT", default="5432"))
    resolved_db = db_name or _database_name()
    resolved_user = _get_env("POSTGRES_USER_NAME", "DB_USER", "POSTGRES_USER", default="admin")
    resolved_password = _get_env("POSTGRES_PASSWORD_VALUE", "DB_PASSWORD", "POSTGRES_PASSWORD", default="admin123")
    return _connect_with_retries(resolved_host, resolved_port, resolved_db, resolved_user, resolved_password)


@contextmanager
def db_context(db_name: str | None = None):
    connection = _get_postgres_connection_server(db_name=db_name)
    try:
        yield connection
    finally:
        connection.close()


def init_db() -> None:
    statements = [
        """
        CREATE TABLE IF NOT EXISTS public.users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            apellido VARCHAR(100) NOT NULL,
            email VARCHAR(255) NOT NULL UNIQUE,
            descripcion VARCHAR(200) NOT NULL,
            password VARCHAR(255) NOT NULL,
            status INTEGER NOT NULL DEFAULT 1,
            startline TIMESTAMPTZ,
            deadline TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            auth_provider VARCHAR(40) NOT NULL DEFAULT 'local',
            google_sub VARCHAR(255),
            avatar_url TEXT,
            given_name VARCHAR(255),
            family_name VARCHAR(255),
            email_verified BOOLEAN NOT NULL DEFAULT FALSE,
            last_login_at TIMESTAMPTZ
        )
        """,
        "ALTER TABLE public.users ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(40) NOT NULL DEFAULT 'local'",
        "ALTER TABLE public.users ADD COLUMN IF NOT EXISTS google_sub VARCHAR(255)",
        "ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar_url TEXT",
        "ALTER TABLE public.users ADD COLUMN IF NOT EXISTS given_name VARCHAR(255)",
        "ALTER TABLE public.users ADD COLUMN IF NOT EXISTS family_name VARCHAR(255)",
        "ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE",
        "ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ",
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ux_users_google_sub
            ON public.users (google_sub)
            WHERE google_sub IS NOT NULL
        """,
        """
        CREATE TABLE IF NOT EXISTS public.proms (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(150),
            data JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    ]

    with db_context() as connection:
        with connection.cursor() as cursor:
            for statement in statements:
                cursor.execute(statement)
        connection.commit()

    logger.info("event=init_db tables=users,proms status=ready")


def init_products_db() -> None:
    statements = [
        """
        CREATE TABLE IF NOT EXISTS public.productos (
            pk_product BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cdgo_producto_externo VARCHAR(200),
            name_product VARCHAR(200) NOT NULL,
            description_product VARCHAR(1000),
            disabled BOOLEAN NOT NULL DEFAULT FALSE,
            price NUMERIC(18,4) DEFAULT 0,
            unit INTEGER NOT NULL DEFAULT 1,
            final_price NUMERIC(18,4) DEFAULT 0,
            discount NUMERIC(18,4) DEFAULT 0,
            discount_end_date TIMESTAMPTZ,
            fk_currency INTEGER NOT NULL DEFAULT 1,
            currency VARCHAR(50),
            user_rating NUMERIC(10,2) NOT NULL DEFAULT 0,
            link VARCHAR(255),
            creation_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            fk_last_update_user BIGINT NOT NULL DEFAULT 1,
            last_update TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            supplier VARCHAR(200)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.products_images (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT REFERENCES public.productos(pk_product) ON DELETE SET NULL,
            original_filename VARCHAR(255),
            stored_filename VARCHAR(255) NOT NULL UNIQUE,
            mime_type VARCHAR(100) NOT NULL,
            file_size BIGINT NOT NULL,
            storage_path TEXT NOT NULL,
            public_url TEXT NOT NULL,
            is_default BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_products_images_product_id
            ON public.products_images (product_id)
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ux_products_images_default_per_product
            ON public.products_images (product_id)
            WHERE is_default = TRUE
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_units (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(20) NOT NULL UNIQUE,
            name VARCHAR(120) NOT NULL,
            description VARCHAR(255),
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_currencies (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            iso_code CHAR(3) NOT NULL UNIQUE,
            name VARCHAR(120) NOT NULL,
            symbol VARCHAR(10),
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_exchange_rates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            currency_id BIGINT NOT NULL REFERENCES public.inventory_currencies(id) ON UPDATE CASCADE,
            rate_to_base NUMERIC(18,6) NOT NULL,
            effective_date DATE NOT NULL,
            source VARCHAR(120),
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(currency_id, effective_date)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_unit_conversions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT REFERENCES public.productos(pk_product) ON DELETE CASCADE,
            from_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            to_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            factor NUMERIC(18,6) NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(product_id, from_unit_id, to_unit_id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_warehouses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(40) NOT NULL UNIQUE,
            name VARCHAR(120) NOT NULL,
            description VARCHAR(255),
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.product_inventory_config (
            product_id BIGINT PRIMARY KEY REFERENCES public.productos(pk_product) ON DELETE CASCADE,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            reorder_point NUMERIC(18,4) NOT NULL DEFAULT 0,
            reorder_quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
            allow_negative_stock BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_suppliers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_code VARCHAR(80) UNIQUE,
            name VARCHAR(200) NOT NULL UNIQUE,
            email VARCHAR(255),
            phone VARCHAR(80),
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_stock_levels (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON DELETE CASCADE,
            warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON DELETE CASCADE,
            physical_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            reserved_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(product_id, warehouse_id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.purchase_orders (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_id BIGINT NOT NULL REFERENCES public.inventory_suppliers(id) ON UPDATE CASCADE,
            warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            purchase_order_number VARCHAR(80) NOT NULL UNIQUE,
            status VARCHAR(40) NOT NULL DEFAULT 'borrador',
            user_name VARCHAR(120) NOT NULL,
            notes TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.purchase_order_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            purchase_order_id BIGINT NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            requested_qty NUMERIC(18,4) NOT NULL,
            received_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            canceled_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            pending_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            currency_id BIGINT NOT NULL REFERENCES public.inventory_currencies(id) ON UPDATE CASCADE,
            currency_code CHAR(3) NOT NULL,
            unit_price NUMERIC(18,4) NOT NULL DEFAULT 0,
            exchange_rate NUMERIC(18,6) NOT NULL DEFAULT 1,
            exchange_rate_date DATE NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.goods_receipts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            purchase_order_id BIGINT NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
            supplier_id BIGINT NOT NULL REFERENCES public.inventory_suppliers(id) ON UPDATE CASCADE,
            warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            receipt_number VARCHAR(80) NOT NULL UNIQUE,
            operation_key VARCHAR(120) NOT NULL UNIQUE,
            status VARCHAR(40) NOT NULL DEFAULT 'borrador',
            user_name VARCHAR(120) NOT NULL,
            notes TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.goods_receipt_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            receipt_id BIGINT NOT NULL REFERENCES public.goods_receipts(id) ON DELETE CASCADE,
            purchase_order_line_id BIGINT NOT NULL REFERENCES public.purchase_order_lines(id) ON DELETE CASCADE,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            received_qty NUMERIC(18,4) NOT NULL,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            currency_id BIGINT NOT NULL REFERENCES public.inventory_currencies(id) ON UPDATE CASCADE,
            currency_code CHAR(3) NOT NULL,
            unit_price NUMERIC(18,4) NOT NULL DEFAULT 0,
            exchange_rate NUMERIC(18,6) NOT NULL DEFAULT 1,
            exchange_rate_date DATE NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.sales_orders (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_name VARCHAR(200) NOT NULL,
            warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            sales_order_number VARCHAR(80) NOT NULL UNIQUE,
            status VARCHAR(40) NOT NULL DEFAULT 'borrador',
            user_name VARCHAR(120) NOT NULL,
            notes TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.sales_order_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sales_order_id BIGINT NOT NULL REFERENCES public.sales_orders(id) ON DELETE CASCADE,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            requested_qty NUMERIC(18,4) NOT NULL,
            reserved_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            dispatched_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            invoiced_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            canceled_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            returned_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            pending_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            currency_id BIGINT NOT NULL REFERENCES public.inventory_currencies(id) ON UPDATE CASCADE,
            currency_code CHAR(3) NOT NULL,
            unit_price NUMERIC(18,4) NOT NULL DEFAULT 0,
            exchange_rate NUMERIC(18,6) NOT NULL DEFAULT 1,
            exchange_rate_date DATE NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_reservations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sales_order_id BIGINT NOT NULL REFERENCES public.sales_orders(id) ON DELETE CASCADE,
            sales_order_line_id BIGINT NOT NULL REFERENCES public.sales_order_lines(id) ON DELETE CASCADE,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            reserved_qty NUMERIC(18,4) NOT NULL,
            released_qty NUMERIC(18,4) NOT NULL DEFAULT 0,
            status VARCHAR(40) NOT NULL DEFAULT 'borrador',
            operation_key VARCHAR(120) NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.sales_dispatches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sales_order_id BIGINT NOT NULL REFERENCES public.sales_orders(id) ON DELETE CASCADE,
            warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            dispatch_number VARCHAR(80) NOT NULL UNIQUE,
            operation_key VARCHAR(120) NOT NULL UNIQUE,
            status VARCHAR(40) NOT NULL DEFAULT 'borrador',
            user_name VARCHAR(120) NOT NULL,
            notes TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.sales_dispatch_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            dispatch_id BIGINT NOT NULL REFERENCES public.sales_dispatches(id) ON DELETE CASCADE,
            sales_order_line_id BIGINT NOT NULL REFERENCES public.sales_order_lines(id) ON DELETE CASCADE,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            dispatched_qty NUMERIC(18,4) NOT NULL,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.sales_invoices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sales_order_id BIGINT NOT NULL REFERENCES public.sales_orders(id) ON DELETE CASCADE,
            invoice_number VARCHAR(80) NOT NULL UNIQUE,
            status VARCHAR(40) NOT NULL DEFAULT 'borrador',
            user_name VARCHAR(120) NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.sales_invoice_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            invoice_id BIGINT NOT NULL REFERENCES public.sales_invoices(id) ON DELETE CASCADE,
            sales_order_line_id BIGINT NOT NULL REFERENCES public.sales_order_lines(id) ON DELETE CASCADE,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            invoiced_qty NUMERIC(18,4) NOT NULL,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.sales_returns (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sales_order_id BIGINT NOT NULL REFERENCES public.sales_orders(id) ON DELETE CASCADE,
            warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            return_number VARCHAR(80) NOT NULL UNIQUE,
            credit_note_number VARCHAR(80) NOT NULL UNIQUE,
            operation_key VARCHAR(120) NOT NULL UNIQUE,
            status VARCHAR(40) NOT NULL DEFAULT 'borrador',
            user_name VARCHAR(120) NOT NULL,
            reason VARCHAR(120) NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.sales_return_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sales_return_id BIGINT NOT NULL REFERENCES public.sales_returns(id) ON DELETE CASCADE,
            sales_order_line_id BIGINT NOT NULL REFERENCES public.sales_order_lines(id) ON DELETE CASCADE,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            returned_qty NUMERIC(18,4) NOT NULL,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_transfers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            destination_warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            transfer_number VARCHAR(80) NOT NULL UNIQUE,
            operation_key VARCHAR(120) NOT NULL UNIQUE,
            status VARCHAR(40) NOT NULL DEFAULT 'borrador',
            user_name VARCHAR(120) NOT NULL,
            reason VARCHAR(120) NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_transfer_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            transfer_id BIGINT NOT NULL REFERENCES public.inventory_transfers(id) ON DELETE CASCADE,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            quantity NUMERIC(18,4) NOT NULL,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.inventory_movements (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            movement_type VARCHAR(60) NOT NULL,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON UPDATE CASCADE,
            warehouse_id BIGINT REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            warehouse_destination_id BIGINT REFERENCES public.inventory_warehouses(id) ON UPDATE CASCADE,
            quantity NUMERIC(18,4) NOT NULL,
            quantity_signed NUMERIC(18,4) NOT NULL,
            base_unit_id BIGINT NOT NULL REFERENCES public.inventory_units(id) ON UPDATE CASCADE,
            document_type VARCHAR(60),
            document_id BIGINT,
            document_line_id BIGINT,
            operation_key VARCHAR(120) NOT NULL,
            reason VARCHAR(120),
            user_name VARCHAR(120) NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.external_data_cache (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source VARCHAR(80) NOT NULL,
            operation VARCHAR(80) NOT NULL,
            cache_key VARCHAR(255) NOT NULL,
            payload JSONB NOT NULL,
            country CHAR(2),
            currency CHAR(3),
            reference_url TEXT,
            queried_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMPTZ NOT NULL,
            UNIQUE(source, operation, cache_key)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.review_batches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON DELETE CASCADE,
            source VARCHAR(80) NOT NULL,
            country CHAR(2),
            currency CHAR(3),
            status VARCHAR(30) NOT NULL,
            total_reviews INTEGER NOT NULL DEFAULT 0,
            summary JSONB,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            completed_at TIMESTAMPTZ
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.product_reviews (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES public.review_batches(id) ON DELETE CASCADE,
            source_review_id VARCHAR(255),
            rating NUMERIC(3,2),
            review_text TEXT NOT NULL,
            sentiment VARCHAR(20) NOT NULL,
            reviewed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.knowledge_documents (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            content TEXT NOT NULL,
            source VARCHAR(120) NOT NULL,
            expires_at TIMESTAMPTZ,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_inventory_stock_levels_product_warehouse
            ON public.inventory_stock_levels (product_id, warehouse_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_inventory_movements_product_warehouse
            ON public.inventory_movements (product_id, warehouse_id, created_at DESC)
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_external_data_cache_source_expiry
            ON public.external_data_cache (source, expires_at DESC)
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_product_reviews_batch
            ON public.product_reviews (batch_id)
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_knowledge_documents_active_expiry
            ON public.knowledge_documents (is_active, expires_at)
        """,
        """
        INSERT INTO public.inventory_units (code, name, description)
        VALUES
            ('unit', 'Unidad', 'Unidad base'),
            ('box', 'Caja', 'Caja o empaque'),
            ('kg', 'Kilogramo', 'Unidad de peso')
        ON CONFLICT (code) DO NOTHING
        """,
        """
        INSERT INTO public.inventory_currencies (iso_code, name, symbol)
        VALUES
            ('EUR', 'Euro', '€'),
            ('USD', 'US Dollar', '$'),
            ('COP', 'Peso Colombiano', '$')
        ON CONFLICT (iso_code) DO NOTHING
        """,
        """
        CREATE TABLE IF NOT EXISTS public.agent_decisions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            requested_agent VARCHAR(50), routed_agent VARCHAR(50) NOT NULL,
            request_data JSONB NOT NULL, response_summary JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.automation_rules (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, description TEXT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT FALSE, interval_minutes INTEGER NOT NULL DEFAULT 1440,
            last_run_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.automation_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            rule_id BIGINT NOT NULL REFERENCES public.automation_rules(id) ON DELETE CASCADE,
            initiated_by VARCHAR(80) NOT NULL, status VARCHAR(30) NOT NULL,
            result JSONB, error_message VARCHAR(500), started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            completed_at TIMESTAMPTZ
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS public.purchase_proposals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            automation_run_id BIGINT REFERENCES public.automation_runs(id) ON DELETE SET NULL,
            product_id BIGINT NOT NULL REFERENCES public.productos(pk_product) ON DELETE CASCADE,
            warehouse_id BIGINT NOT NULL REFERENCES public.inventory_warehouses(id) ON DELETE CASCADE,
            suggested_qty NUMERIC(18,4) NOT NULL, base_unit_code VARCHAR(20) NOT NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'pending_approval', justification TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_automation_runs_rule_started
            ON public.automation_runs (rule_id, started_at DESC)
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_purchase_proposals_pending
            ON public.purchase_proposals (status, product_id, warehouse_id)
        """,
    ]

    with db_context() as connection:
        with connection.cursor() as cursor:
            for statement in statements:
                cursor.execute(statement)
        connection.commit()

    logger.info("event=init_products_db tables=productos,inventory status=ready")


def get_db() -> Generator[Any, None, None]:
    connection = _get_postgres_connection_server()
    try:
        yield connection
    finally:
        connection.close()


def get_db_products() -> Generator[Any, None, None]:
    connection = _get_postgres_connection_server()
    try:
        yield connection
    finally:
        connection.close()


def get_db_memori() -> Generator[Any, None, None]:
    connection = _get_postgres_connection_server()
    try:
        yield connection
    finally:
        connection.close()


def get_db_users() -> Generator[Any, None, None]:
    connection = _get_postgres_connection_server()
    try:
        yield connection
    finally:
        connection.close()
