-- Proyecto Jupiter: clientes, direcciones y esquema comercial (2026-09-08).
CREATE TABLE IF NOT EXISTS public.type_client (
    pk_type_client BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

INSERT INTO public.type_client (pk_type_client, name) VALUES
    (1, 'Propio'), (2, 'Prospecto'), (3, 'Confirmado'),
    (4, 'Activo'), (5, 'Desactivado'), (6, 'Suspendido')
ON CONFLICT (pk_type_client) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('public.type_client', 'pk_type_client'),
    GREATEST((SELECT COALESCE(MAX(pk_type_client), 1) FROM public.type_client), 1), true
);

CREATE TABLE IF NOT EXISTS public.clients (
    pk_client BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_code TEXT,
    name VARCHAR(250) NOT NULL,
    description VARCHAR(255),
    fk_type_client BIGINT NOT NULL DEFAULT 1 CONSTRAINT fk_clients_type_client REFERENCES public.type_client(pk_type_client) ON UPDATE CASCADE ON DELETE RESTRICT,
    creation_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fk_last_update_user BIGINT DEFAULT 1
);

ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS client_code TEXT;

CREATE TABLE IF NOT EXISTS public.globlal_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_line_1 VARCHAR(255) NOT NULL, address_line_2 VARCHAR(255), city VARCHAR(120) NOT NULL,
    state_province VARCHAR(120), postal_code VARCHAR(32), country_code CHAR(2) NOT NULL,
    country_name VARCHAR(120), latitude NUMERIC(10,7), longitude NUMERIC(10,7),
    contact_name VARCHAR(200), contact_phone VARCHAR(80), contact_email VARCHAR(255), notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.clients_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES public.clients(pk_client) ON DELETE CASCADE,
    global_address_id BIGINT NOT NULL REFERENCES public.globlal_addresses(id) ON DELETE RESTRICT,
    address_type VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_clients_addresses_type CHECK (address_type IN ('Dirección principal', 'Dirección por defecto', 'Dirección de entrega', 'Dirección de Recogida')),
    UNIQUE (client_id, global_address_id, address_type)
);

CREATE INDEX IF NOT EXISTS ix_clients_addresses_client_id ON public.clients_addresses (client_id);

CREATE INDEX IF NOT EXISTS ix_clients_addresses_global_address_id ON public.clients_addresses (global_address_id);

CREATE TABLE IF NOT EXISTS public.inventory_suppliers_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL REFERENCES public.inventory_suppliers(id) ON DELETE CASCADE,
    global_address_id BIGINT NOT NULL REFERENCES public.globlal_addresses(id) ON DELETE RESTRICT,
    address_type VARCHAR(40) NOT NULL CHECK (address_type IN ('Dirección principal', 'Dirección por defecto', 'Dirección de entrega', 'Dirección de Recogida')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (supplier_id, global_address_id, address_type)
);

CREATE INDEX IF NOT EXISTS ix_inventory_suppliers_addresses_supplier_id ON public.inventory_suppliers_addresses (supplier_id);

CREATE TABLE IF NOT EXISTS public.error_log
    (
        pk_error BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        error_title character varying COLLATE pg_catalog."default",
        error_description character varying COLLATE pg_catalog."default",
        create_date timestamp with time zone,
        pfk_user integer
    );

CREATE TABLE IF NOT EXISTS public.properties
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property character varying(500) COLLATE pg_catalog."default" NOT NULL,
        value character varying(500) COLLATE pg_catalog."default",
        valueint bigint,
        valuedate timestamp without time zone,
        creation_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint NOT NULL DEFAULT 1,
        last_update timestamp with time zone,
        CONSTRAINT propertyunique UNIQUE (property)
    );

CREATE TABLE IF NOT EXISTS public.currency
    (
        pk_currency BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name character varying(250) COLLATE pg_catalog."default",
        symbol character varying(3) COLLATE pg_catalog."default"
    );

CREATE TABLE IF NOT EXISTS public.type_catalog
    (
        pk_type_catalog BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name character varying(250) COLLATE pg_catalog."default"
    );

CREATE TABLE IF NOT EXISTS public.type_funding_source
    (
        pk_type_funding_source BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name character varying(250) COLLATE pg_catalog."default"
    );

CREATE TABLE IF NOT EXISTS public.catalogues
    (
        pk_catalog BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name_catalog character varying(250) COLLATE pg_catalog."default" NOT NULL,
        start_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        end_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_type_catalog integer DEFAULT 1,
        creation_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint DEFAULT 1
    );

CREATE TABLE IF NOT EXISTS public.catalogues_products
    (
        pk_catalog_product BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pk_catalog bigint NOT NULL,
        pk_product bigint NOT NULL,
        creation_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint NOT NULL DEFAULT 1
    );

CREATE TABLE IF NOT EXISTS public.markets
    (
        pk_market BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name_market character varying COLLATE pg_catalog."default",
        disabled boolean NOT NULL DEFAULT false,
        link TEXT,
        description character varying(255) COLLATE pg_catalog."default",
        creation_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint DEFAULT 1
    );

CREATE TABLE IF NOT EXISTS public.markets_catalogues
    (
        pk_market_catalog BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fk_market bigint NOT NULL DEFAULT 1,
        fk_catalog bigint NOT NULL DEFAULT 1,
        disabled boolean DEFAULT false,
        fk_client_origin bigint,
        fk_client_destination bigint,
        fk_type_funding_source integer DEFAULT 1,
        creation_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint DEFAULT 1
	);

CREATE INDEX IF NOT EXISTS ix_inventory_suppliers_addresses_global_address_id ON public.inventory_suppliers_addresses(global_address_id);

ALTER TABLE public.proms ADD COLUMN IF NOT EXISTS id_prom BIGINT GENERATED ALWAYS AS (id) STORED;

CREATE UNIQUE INDEX IF NOT EXISTS ux_proms_id_prom ON public.proms(id_prom);

ALTER TABLE public.proms ADD COLUMN IF NOT EXISTS nombre VARCHAR(250);

ALTER TABLE public.proms ADD COLUMN IF NOT EXISTS prom TEXT;

ALTER TABLE public.proms ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS ux_productos_cdgo_producto_externo ON public.productos(cdgo_producto_externo) WHERE cdgo_producto_externo IS NOT NULL;

CREATE OR REPLACE VIEW public.ultimos_productos_creados
    AS
    WITH max_date AS (
            SELECT max(productos.last_update) AS max_last_update
            FROM productos
            )
    SELECT TRIM(BOTH FROM p.cdgo_producto_externo) AS cdgo_producto_externo,
        TRIM(BOTH FROM p.name_product) AS name_product,
        TRIM(BOTH FROM p.description_product) AS description_product,
        TRIM(BOTH FROM p.supplier) AS supplier,
        p.last_update
    FROM productos p
        JOIN max_date md ON p.last_update >= (md.max_last_update - '2 days'::interval) AND p.last_update <= CURRENT_TIMESTAMP
    ORDER BY (TRIM(BOTH FROM p.cdgo_producto_externo)) DESC;

CREATE OR REPLACE FUNCTION public.set_last_update_timestamp()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- Al crear el registro: poner ambas fechas si vienen nulas
        IF NEW.creation_date IS NULL THEN
            NEW.creation_date := CURRENT_TIMESTAMP;
        END IF;

        IF NEW.last_update IS NULL THEN
            NEW.last_update := CURRENT_TIMESTAMP;
        END IF;

    ELSIF TG_OP = 'UPDATE' THEN
        -- En actualización: mantener la fecha de creación
        NEW.creation_date := OLD.creation_date;

        -- y actualizar solo la de última modificación
        NEW.last_update := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_update_last_update BEFORE INSERT OR UPDATE ON public.productos FOR EACH ROW EXECUTE FUNCTION public.set_last_update_timestamp();
